version: "2"
services:
  website:
    restart: always
    build: ./website
    expose:
      - "8000"
    volumes:
      - ./website:/usr/src/app
    env_file: .env
    command: /usr/local/bin/gunicorn mysite.wsgi:application -w 2 -b 0.0.0.0:8000 --reload

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - /www/static
    volumes_from:
      - website
    links:
      - website